language: c
compiler:
  - gcc
  - clang
script:
  - s/build
  - s/runtests
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libfcgi-dev autotools-dev
os:
  - linux
  - osx
notifications:
  slack:
      secure: F89aXLWaE125PaJIlETv12jT4EfH6wLXJmGCPZzrN3OcLn2ahDWqjwuzR7lOEDf2nAISmeMPyDZMhEHXLNHAE5qP6lg9yliYQw5hzGmDK9m1xUq/pPEne/b2Y7K3my1mkRZ6n3asbHgSmBWAfCIk1JN8R5Rv+rmbLuWLc+zofts=
